services:
  manticore:
    image: ghcr.io/manticoresoftware/manticoresearch:test-kit-fix_performance-mcl
    container_name: upload-compare-manticore
    entrypoint: ["searchd"]
    command: ["--config", "/etc/manticoresearch/manticore.conf", "--nodetach"]
    ports:
      - "19306:9306"
      - "19308:9308"
    volumes:
      - ./data/manticore:/var/lib/manticore

  typesense:
    image: typesense/typesense:30.1
    container_name: upload-compare-typesense
    ports:
      - "18108:8108"
    command: >
      --data-dir /data
      --api-key=xyz
      --enable-cors
    volumes:
      - ./data/typesense:/data
